'use client'
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import './globals.css';
import { useEffect, useState } from "react";

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // pilih sesuai kebutuhan
  variable: '--font-montserrat',
})

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter();
  const [openMenu, setOpenMenu] = useState(false);
  // const [currentPage, setCurrentPage] = useState(false);

  return (
    <html lang="en" className={montserrat.variable}>
      <title>
        Guruverse.ID | Bukan sekadar nama. Ia adalah manifestasi dari ekosistem yang dibangun oleh ACF Eduhub.
        Sebuah ruang di mana guru bertumbuh secara kompeten, sejahtera, dan bahagia. Menghadirkan kehangatan dalam kebersamaan,spiritualitas dalam setiap langkah,dan arah gerakan yang membumi, namun tetap visioner.
        Kami mempunyai tujuan besar untuk membangun ekosistem pendidikan yang memberdayakan guru secara kompetensi, ekonomi, dan spiritual sebagai fondasi peradaban yang berkelanjutan.
      </title>
      <body
        className=""
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full lg:max-w-full max-w-lg overflow-x-hidden  h-auto min-h-screen overflow-y-auto bg-body mx-auto ">
          <div className="flex justify-between items-center lg:m-4 m-2">
            <img src="/svg/logo-colorfull.svg" className="lg:h-20 h-12 w-auto cursor-pointer" onClick={() => router.push("/")} />
            <div className="lg:flex mr-4 hidden ">
              <button className="mr-4 cursor-pointer" onClick={() => router.push("/about-us")}>
                {/* ${currentPage == "about-us" ? "text-secondary" : "text-primary"} */}
                <span className={` text-primary font-semibold hover:text-secondary `}>Tentang Kami</span>
              </button>
              <button className="border-2  cursor-pointer h-12 px-10 font-semibold rounded-3xl border-primary text-primary hover:text-secondary hover:border-secondary" onClick={() => window.open("https://api.whatsapp.com/send?phone=6283133531303&text=Halo%20kak,%20saya%20mau%20tanya%20tentang%20Guruverse.ID")}>
                <span className="text-lg">Contact Us</span>
              </button>
            </div>
            <div className="flex mr-4 lg:hidden ">
              <img src="/svg/menu.svg" className=" w-8 h-auto cursor-pointer z-10" onClick={() => setOpenMenu(!openMenu)} />
            </div>
          </div>
          {
            <aside
              className={`lg:hidden fixed inset-y-0 right-0 w-64 bg-white shadow-lg transform transition-transform duration-300 z-50
        ${openMenu ? "translate-x-0" : "translate-x-full"}
        lg:translate-x-0 lg:static lg:ml-auto`}
            >
              <div className="p-6 border-b flex justify-between items-center">
                <h2 className="text-xl font-semibold">Menu</h2>

                {/* Close button mobile */}
                <button
                  onClick={() => setOpenMenu(false)}
                  className="lg:hidden p-2"
                >
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" strokeWidth="2"
                    viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>

              <nav className="p-4 space-y-2">
                <a href="/" className="block px-4 py-2 rounded hover:bg-gray-200">Home</a>
                <a href="/about-us" className="block px-4 py-2 rounded hover:bg-gray-200">Tentang Kami</a>
                <a href="/guru-kompeten" className="block px-4 py-2 rounded hover:bg-gray-200">Guru Kompeten</a>
                <a href="https://sharinghappiness.org/profile/1650733" className="block px-4 py-2 rounded hover:bg-gray-200">Guru Sejahtera </a>
                <a href="https://www.instagram.com/ceriatraining?igsh=dHl3ZG5nM3E4MTFo" className="block px-4 py-2 rounded hover:bg-gray-200">Guru Bahagia </a>
              </nav>
            </aside>
          }
          {children}
          <footer className="flex justify-between items-end bg-secondary lg:pb-8 pb-0 lg:pt-28 pt-0 lg:pr-0 pr-8">
            <div className="mt-16  lg:mx-10 mx-4 relative z-10 flex flex-col">
              <img src="/svg/logo-white.svg" className=" lg:w-32 w-28 h-auto mb-6 cursor-pointer lg:order-1 order-2" onClick={() => router.push("/")} />
              <div className="lg:order-2 order-1 mb-4 lg:mb-0">
                <p className="text-sm lg:text-lg font-bold text-white ml-3">Alamat</p>
                <p className="text-sm lg:text-lg text-white ml-3 cursor-pointer" onClick={() => window.open("https://maps.app.goo.gl/BxickKBZeqStR7Gx9")}>
                  Komplek Jatimulya Jl. Jati Mulya No. 9, Gumuruh, <br />Kec. Batununggal, Kota Bandung, Jawa Barat 40275</p>
              </div>
            </div>
            <div className="flex gap-4 mr-10 relative z-10">
              <img src="/svg/instagram.svg" className=" w-10 h-auto mb-6 cursor-pointer" onClick={() => window.open("https://www.instagram.com/ceriatraining?igsh=dHl3ZG5nM3E4MTFo")} />
              <img src="/svg/youtube.svg" className=" w-10 h-auto mb-6 cursor-pointer" onClick={() => window.open("https://www.youtube.com/@JUARATV")} />
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
